name: quality
on: [pull_request]
jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs $(nproc) --retry 3
      - run: 'bundle exec rake lint'
      - run: 'bundle exec rake rubocop'
